import { createHash, createHmac, timingSafeEqual } from 'node:crypto';
import { mkdir, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { createReadStream } from 'node:fs';
import path from 'node:path';

import type { DocumentProvider, ObjectMetadata, SignedUrl } from './document-provider.js';

/**
 * Files on disk, with real signatures and real expiry (ADR-0008).
 *
 * The development host has no S3 and no Docker, so this is what runs locally
 * and in CI. It stores bytes under `.storage/` — the easy part — and then
 * does the part that matters: it **emulates the security semantics** rather
 * than skipping them.
 *
 * A "signed URL" here is an HMAC over the key, the operation, and an expiry,
 * verified by an API route that also re-checks the caller's authorisation. So
 * the failure modes a developer meets locally are the failure modes
 * production has: a link that has expired, a signature that does not verify, a
 * key that was tampered with. An adapter that returned `/files/{key}` and
 * served it would make every one of those appear for the first time in
 * staging.
 *
 * ## Keys never come from a file name
 *
 * They are generated by the caller from a UUID and validated here against a
 * strict pattern. A key containing `..` is refused rather than normalised,
 * because normalising is how a traversal becomes a bug in the normaliser.
 */
export class LocalDocumentProvider implements DocumentProvider {
  readonly providerKey = 'local';
  readonly isSandbox = true;

  constructor(
    private readonly root: string,
    private readonly secret: string,
    /** Where the signed link points — the API's own base URL. */
    private readonly baseUrl: string,
  ) {}

  createUploadUrl(
    key: string,
    contentType: string,
    maxBytes: number,
    ttlSeconds: number,
  ): Promise<SignedUrl> {
    const expiresAt = new Date(Date.now() + ttlSeconds * 1000);
    const token = this.sign('PUT', key, expiresAt);

    const url = new URL(
      `${this.baseUrl.replace(/\/$/, '')}/v1/documents/${encodeURIComponent(key)}`,
    );
    url.searchParams.set('token', token);
    url.searchParams.set('expires', String(expiresAt.getTime()));
    // Carried so the route can refuse a mismatch early; the authoritative
    // check is still the magic-byte read at completion.
    url.searchParams.set('contentType', contentType);
    url.searchParams.set('maxBytes', String(maxBytes));

    return Promise.resolve({ url: url.toString(), expiresAt });
  }

  createDownloadUrl(key: string, ttlSeconds: number, fileName: string): Promise<SignedUrl> {
    const expiresAt = new Date(Date.now() + ttlSeconds * 1000);
    const token = this.sign('GET', key, expiresAt);

    const url = new URL(
      `${this.baseUrl.replace(/\/$/, '')}/v1/documents/${encodeURIComponent(key)}`,
    );
    url.searchParams.set('token', token);
    url.searchParams.set('expires', String(expiresAt.getTime()));
    url.searchParams.set('name', fileName);

    // Signing is pure here; the promise is the port's shape rather than this
    // adapter's need, and S3's implementation genuinely awaits.
    return Promise.resolve({ url: url.toString(), expiresAt });
  }

  async getObjectMetadata(key: string): Promise<ObjectMetadata | null> {
    const file = this.resolve(key);

    try {
      const info = await stat(file);
      const data = await readFile(file);

      return {
        byteSize: info.size,
        // The stored type is whatever the bytes say it is; this adapter keeps
        // no separate content-type record, which is deliberate — one source of
        // truth about a file's type, and it is the file.
        contentType: 'application/octet-stream',
        checksum: createHash('sha256').update(data).digest('hex'),
      };
    } catch {
      return null;
    }
  }

  async readHeader(key: string, byteCount: number): Promise<Uint8Array | null> {
    const file = this.resolve(key);

    return new Promise((resolve) => {
      const chunks: Buffer[] = [];
      const stream = createReadStream(file, { start: 0, end: byteCount - 1 });

      stream.on('data', (chunk) => chunks.push(chunk as Buffer));
      stream.on('end', () => {
        resolve(Uint8Array.from(Buffer.concat(chunks)));
      });
      // A missing object is `null`, not a throw: "there is nothing there" is
      // an answer the completion step handles, and it is the ordinary outcome
      // when somebody abandoned an upload.
      stream.on('error', () => {
        resolve(null);
      });
    });
  }

  async replaceObject(key: string, data: Uint8Array): Promise<void> {
    const file = this.resolve(key);

    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, data);
  }

  async read(key: string): Promise<Uint8Array | null> {
    try {
      return Uint8Array.from(await readFile(this.resolve(key)));
    } catch {
      return null;
    }
  }

  async deleteObject(key: string): Promise<void> {
    await rm(this.resolve(key), { force: true });
  }

  // ── the signature ────────────────────────────────────────────────────────

  /**
   * The signature covers the operation as well as the key and the expiry.
   *
   * Without the operation, a link that lets somebody *read* a receipt is the
   * same string that lets them *overwrite* it — and the read link is the one
   * that gets pasted into a chat message.
   */
  sign(operation: 'GET' | 'PUT', key: string, expiresAt: Date): string {
    return createHmac('sha256', this.secret)
      .update(`${operation}:${key}:${String(expiresAt.getTime())}`)
      .digest('hex');
  }

  /**
   * Verify a presented token.
   *
   * Compared with `timingSafeEqual`, and expiry is checked as well as the
   * signature — a valid signature on an expired link is exactly the case this
   * has to refuse, and it is the one a naive check gets wrong.
   */
  verify(operation: 'GET' | 'PUT', key: string, expiresAtMs: number, token: string): boolean {
    if (!Number.isFinite(expiresAtMs) || expiresAtMs < Date.now()) return false;

    const expected = Buffer.from(this.sign(operation, key, new Date(expiresAtMs)), 'utf8');
    const presented = Buffer.from(token, 'utf8');

    if (expected.length !== presented.length) return false;

    return timingSafeEqual(expected, presented);
  }

  /**
   * A key is `<uuid>/<uuid>` and nothing else.
   *
   * Validated rather than normalised: `receipts/../../etc/passwd` is refused
   * outright, because a normaliser is a thing with bugs and a pattern is not.
   */
  private resolve(key: string): string {
    if (!/^[0-9a-f-]{36}\/[0-9a-f-]{36}$/i.test(key)) {
      throw new Error(`Refusing a storage key that is not two identifiers: ${key}`);
    }

    return path.join(this.root, key);
  }
}
